# Profile Hub for Pimoroni Tufty 2350 / Badgeware.
#
# Runtime layout and drawing proportions are based on the physically tested
# project ZIPs. Configuration and QR data are still generated by build_profile.py.

try:
    import os
    import sys
    import time as _time
except ImportError:  # pragma: no cover - host safety.
    os = None
    sys = None
    _time = None


def _bootstrap_app_dir():
    if os is None or sys is None:
        return
    for candidate in (
        "/apps/profile_hub",
        "/system/apps/profile_hub",
        "/system/contrib/profile_hub",
    ):
        try:
            os.stat(candidate)
        except OSError:
            continue
        try:
            os.chdir(candidate)
        except OSError:
            pass
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
        return


_bootstrap_app_dir()

try:
    from . import profile_config as cfg
    from .generated_qr import QR_CODES
    from .network_manager import NetworkManager
    from . import wdgwars
    from . import wigle
except ImportError:  # Badgeware loads app-folder modules as top-level files.
    import profile_config as cfg
    from generated_qr import QR_CODES
    from network_manager import NetworkManager
    import wdgwars
    import wigle


try:
    badge.mode(HIRES | VSYNC)
    screen.antialias = image.X4
    BADGEWARE_READY = True
except Exception:
    BADGEWARE_READY = False


W = 320
H = 240
APP_START_TICKS = 0
if BADGEWARE_READY:
    W = screen.width
    H = screen.height
    APP_START_TICKS = badge.ticks
    MONA = font.load("/system/assets/fonts/MonaSans-Medium.af")
    PIXEL = font.winds
else:
    MONA = None
    PIXEL = None


if BADGEWARE_READY:
    BG = color.rgb(6, 10, 14)
    BG_SOFT = color.rgb(10, 17, 22)
    PANEL = color.rgb(14, 23, 28)
    PANEL_2 = color.rgb(22, 35, 42)
    LINE = color.rgb(36, 56, 64)
    WHITE = color.rgb(238, 242, 236)
    OFF_WHITE = color.rgb(200, 209, 201)
    DIM = color.rgb(118, 140, 136)
    BLACK = color.rgb(0, 0, 0)
    PCB_GREEN = color.rgb(52, 102, 74)
    PCB_GREEN_BRIGHT = color.rgb(92, 166, 108)
    GOLD = color.rgb(214, 172, 84)
    CYAN = color.rgb(74, 164, 224)
    RED = color.rgb(205, 78, 78)
    ORANGE = color.rgb(221, 128, 64)
    STATUS_GREEN = color.rgb(96, 196, 120)
    BLUE = color.rgb(86, 134, 220)
else:
    BG = BG_SOFT = PANEL = PANEL_2 = LINE = None
    WHITE = OFF_WHITE = DIM = BLACK = None
    PCB_GREEN = PCB_GREEN_BRIGHT = GOLD = CYAN = RED = ORANGE = STATUS_GREEN = BLUE = None


ACCENTS = {
    "cyan": CYAN,
    "red": RED,
    "orange": ORANGE,
    "green": PCB_GREEN_BRIGHT,
    "gold": GOLD,
    "blue": BLUE,
}

LINKS_BY_ID = {}
for item in cfg.LINKS:
    LINKS_BY_ID[item["id"]] = item

PAGES = list(getattr(cfg, "PAGE_ORDER", ["main"]))
if not PAGES or PAGES[0] != "main":
    PAGES = ["main"] + [item for item in PAGES if item != "main"]

page_index = 0
last_input = None
last_page_id = None

NETWORK = NetworkManager(getattr(cfg, "WIFI_NETWORKS", []))

wdg_data = None
wdg_status = "IDLE"
wdg_last_success = None
wdg_last_attempt = None
wdg_next_auto = None
wdg_refresh_pending = None

wigle_data = None
wigle_status = "IDLE"
wigle_last_success = None
wigle_last_attempt = None
wigle_next_auto = None
wigle_refresh_pending = None


def ticks_elapsed(now, previous):
    if previous is None:
        return 1 << 30
    if _time is not None and hasattr(_time, "ticks_diff"):
        try:
            return _time.ticks_diff(now, previous)
        except Exception:
            pass
    diff = int(now) - int(previous)
    wrap = 1 << 30
    half = wrap >> 1
    if diff < -half:
        return diff + wrap
    if diff > half:
        return diff - wrap
    return diff


def attempt_ready(now, last_attempt, cooldown_ms):
    return ticks_elapsed(now, last_attempt) >= cooldown_ms


def ticks_add(ticks, delta):
    return int(ticks) + int(delta)


def offline_status(previous):
    return "CACHED" if previous is not None else "OFFLINE"


wdg_next_auto = ticks_add(APP_START_TICKS, cfg.WDGWARS_REFRESH_MS)
wigle_next_auto = ticks_add(APP_START_TICKS, cfg.WIGLE_REFRESH_MS)


def vmeasure(text, size):
    screen.font = MONA
    return int(screen.measure_text(str(text), size)[0])


def vtext(text, x, y, size, pen=WHITE):
    screen.font = MONA
    screen.pen = pen
    screen.text(str(text), int(x), int(y), size)


def vright(text, right_x, y, size, pen=WHITE):
    vtext(text, right_x - vmeasure(text, size), y, size, pen)


def fit(text, max_width, size):
    text = str(text)
    if vmeasure(text, size) <= max_width:
        return text
    while text and vmeasure(text + "...", size) > max_width:
        text = text[:-1]
    return text + "..."


def fmt_num(value):
    try:
        text = str(int(value))
    except Exception:
        return "--"
    result = ""
    while len(text) > 3:
        result = "," + text[-3:] + result
        text = text[:-3]
    return text + result


def rank_text(value):
    try:
        value = int(value)
        return "#" + str(value) if value > 0 else "--"
    except Exception:
        return "--"


def clear():
    screen.pen = BG
    screen.clear()

    screen.pen = BG_SOFT
    for x in range(0, W, 32):
        screen.rectangle(x, 0, 1, H)
    for y in range(0, H, 32):
        screen.rectangle(0, y, W, 1)

    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(12, 11, 38, 2)
    screen.pen = GOLD
    screen.rectangle(52, 11, 16, 2)
    screen.pen = OFF_WHITE
    screen.rectangle(W - 44, 11, 32, 2)


def outline(x, y, w, h, accent=PCB_GREEN_BRIGHT, strong=False):
    screen.pen = PANEL
    screen.rectangle(x, y, w, h)

    screen.pen = LINE
    screen.rectangle(x, y, w, 1)
    screen.rectangle(x, y + h - 1, w, 1)
    screen.rectangle(x, y, 1, h)
    screen.rectangle(x + w - 1, y, 1, h)

    thickness = 2 if strong else 1
    screen.pen = accent
    screen.rectangle(x, y, min(48, w), thickness)
    screen.rectangle(x + w - min(22, w), y + h - thickness, min(22, w), thickness)


def footer():
    screen.font = PIXEL
    screen.pen = DIM
    screen.text("A BACK", 12, 221)
    screen.text("B NEXT", 137, 221)
    screen.text("C HOME", 266, 221)

    total = len(PAGES)
    start = int((W - (total * 8 + max(0, total - 1) * 4)) / 2)
    for i in range(total):
        screen.pen = PCB_GREEN_BRIGHT if i == page_index else LINE
        screen.rectangle(start + i * 12, 235, 8, 2)


def draw_xiao_c5(x, y, scale=1):
    bw = 54 * scale
    bh = 74 * scale

    screen.pen = PCB_GREEN
    screen.rectangle(x, y, bw, bh)

    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(x, y, bw, 2)
    screen.rectangle(x, y + bh - 2, bw, 2)
    screen.rectangle(x, y, 2, bh)
    screen.rectangle(x + bw - 2, y, 2, bh)

    screen.pen = OFF_WHITE
    screen.rectangle(x + 17 * scale, y - 3 * scale, 20 * scale, 7 * scale)
    screen.pen = BG
    screen.rectangle(x + 21 * scale, y - 1 * scale, 12 * scale, 3 * scale)

    screen.pen = PANEL_2
    screen.rectangle(x + 13 * scale, y + 18 * scale, 28 * scale, 20 * scale)
    screen.pen = GOLD
    screen.rectangle(x + 13 * scale, y + 18 * scale, 28 * scale, 1)
    screen.rectangle(x + 13 * scale, y + 37 * scale, 28 * scale, 1)
    vtext("C5", x + 19 * scale, y + 23 * scale, 10, OFF_WHITE)

    screen.pen = OFF_WHITE
    screen.rectangle(x + 16 * scale, y + 46 * scale, 10 * scale, 6 * scale)
    screen.rectangle(x + 30 * scale, y + 46 * scale, 8 * scale, 8 * scale)

    screen.pen = GOLD
    py = y + 12 * scale
    for i in range(7):
        screen.rectangle(x - 3 * scale, py + i * 8 * scale, 5 * scale, 4 * scale)
        screen.rectangle(x + bw - 2 * scale, py + i * 8 * scale, 5 * scale, 4 * scale)


def draw_xiao_small(x, y):
    screen.pen = PCB_GREEN
    screen.rectangle(x, y, 28, 36)
    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(x, y, 28, 1)
    screen.rectangle(x, y + 35, 28, 1)
    screen.rectangle(x, y, 1, 36)
    screen.rectangle(x + 27, y, 1, 36)

    screen.pen = OFF_WHITE
    screen.rectangle(x + 8, y - 2, 12, 4)

    screen.pen = PANEL_2
    screen.rectangle(x + 7, y + 10, 14, 10)

    screen.pen = GOLD
    for i in range(4):
        screen.rectangle(x - 2, y + 8 + i * 7, 4, 3)
        screen.rectangle(x + 26, y + 8 + i * 7, 4, 3)

    vtext("C5", x + 9, y + 13, 7, OFF_WHITE)


def draw_main():
    clear()

    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(20, 28, 3, 156)
    screen.pen = GOLD
    screen.rectangle(20, 28, 3, 30)

    draw_xiao_c5(32, 36, 1)

    vtext(cfg.NAME_LINE1, 112, 36, 24, OFF_WHITE)
    vtext(fit(cfg.NAME_LINE2, W - 124, 28), 112, 66, 28, CYAN)
    vtext(fit(cfg.JOB_TITLE, W - 60, 16), 30, 124, 16, OFF_WHITE)

    screen.pen = LINE
    screen.rectangle(30, 151, W - 60, 1)
    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(30, 151, 78, 3)
    screen.pen = GOLD
    screen.rectangle(110, 151, 22, 3)

    vtext(fit(cfg.PRIMARY_LABEL, W - 60, 20), 30, 166, 20, PCB_GREEN_BRIGHT)
    vtext(fit(cfg.TAGLINE, W - 60, 12), 30, 194, 12, DIM)

    footer()


def draw_qr_matrix(n, rows, x, y, scale):
    span = n * scale
    quiet = 4 * scale

    screen.pen = WHITE
    screen.rectangle(x - quiet, y - quiet, span + quiet * 2, span + quiet * 2)

    screen.pen = BLACK
    for row in range(n):
        bits = int(rows[row], 16)
        for col in range(n):
            if bits & (1 << (n - 1 - col)):
                screen.rectangle(x + col * scale, y + row * scale, scale, scale)


def draw_link(page_id):
    clear()

    link = LINKS_BY_ID.get(page_id)
    qr = QR_CODES.get(page_id)

    if not link or not qr:
        vtext("QR DATA MISSING", 22, 30, 22, RED)
        vtext(page_id, 22, 62, 14, DIM)
        footer()
        return

    accent = ACCENTS.get(link.get("accent", "cyan"), CYAN)
    n, rows = qr

    vtext(fit(link["title"], 145, 23), 22, 24, 23, accent)
    vtext(fit(link["label"], 145, 14), 22, 54, 14, OFF_WHITE)
    vtext("SCAN TO OPEN", 22, 76, 11, DIM)

    screen.pen = PCB_GREEN_BRIGHT
    screen.rectangle(22, 98, 42, 2)
    screen.pen = GOLD
    screen.rectangle(66, 98, 16, 2)

    max_side = 132
    scale = max(1, max_side // n)
    span = n * scale
    quiet = 4 * scale
    total = span + quiet * 2
    qx = W - 22 - total + quiet
    qy = 50 + quiet
    draw_qr_matrix(n, rows, qx, qy, scale)

    draw_xiao_small(31, 118)
    vtext("PROFILE", 27, 166, 15, OFF_WHITE)

    footer()


def rank_card(x, y, w, label, value, accent, hero=False):
    h = 51 if hero else 45
    outline(x, y, w, h, accent, hero)
    vtext(label, x + 8, y + 7, 11, accent if hero else DIM)
    if hero:
        vright(rank_text(value), x + w - 8, y + 18, 27, OFF_WHITE)
    else:
        vright(rank_text(value), x + w - 8, y + 18, 18, OFF_WHITE)


def stat_card(x, y, w, label, value, accent):
    outline(x, y, w, 52, accent, False)
    vtext(label, x + 7, y + 7, 10, accent)
    vtext(fit(fmt_num(value), w - 14, 17), x + 7, y + 25, 17, OFF_WHITE)


def status_line(status):
    pen = STATUS_GREEN if status == "LIVE" else ORANGE
    screen.pen = pen
    screen.rectangle(W - 74, 221, 5, 5)
    vtext(status, W - 64, 217, 9, pen)


def draw_wdgwars():
    clear()

    if not cfg.WDGWARS_API_KEY:
        draw_xiao_small(24, 26)
        vtext("WDGWARS", 68, 24, 22, CYAN)
        vtext("SET API KEY", 24, 86, 20, ORANGE)
        vtext("Run builder with credentials.json", 24, 120, 12, DIM)
        footer()
        return

    d = wdg_data or {}

    draw_xiao_small(24, 22)
    username = d.get("username") or "WDGWARS"
    vtext(fit(str(username).upper(), 150, 21), 64, 18, 21, CYAN)

    meta = ""
    if d.get("gang"):
        meta = str(d.get("gang"))
    if d.get("role"):
        meta += (" // " if meta else "") + str(d.get("role")).upper()
    if meta:
        vtext(fit(meta, W - 78, 11), 64, 47, 11, OFF_WHITE)

    sub = ""
    if d.get("country"):
        sub = str(d.get("country")).upper()
    if d.get("since"):
        sub += (" // " if sub else "") + "SINCE " + str(d.get("since"))[:10]
    if sub:
        vtext(fit(sub, 172, 10), 64, 66, 10, DIM)

    if d.get("patron"):
        vright("PATRON", W - 15, 65, 10, STATUS_GREEN)

    vtext("WORLD RANK", 15, 89, 11, DIM)
    rank_card(15, 104, 72, "TODAY", d.get("rank_day"), GOLD, False)
    rank_card(94, 104, 70, "WEEK", d.get("rank_week"), CYAN, False)
    rank_card(171, 98, W - 186, "ALL-TIME", d.get("rank_all"), PCB_GREEN_BRIGHT, True)

    gap = 6
    sw = (W - 30 - gap * 2) // 3
    sy = 160
    stat_card(15, sy, sw, "WI-FI", d.get("wifi"), PCB_GREEN_BRIGHT)
    stat_card(15 + sw + gap, sy, sw, "BLUETOOTH", d.get("ble"), GOLD)
    stat_card(15 + (sw + gap) * 2, sy, sw, "AIRCRAFTS", d.get("aircraft"), CYAN)

    status_line(wdg_status)
    footer()


def draw_wigle():
    clear()

    if not cfg.WIGLE_API_NAME or not cfg.WIGLE_API_TOKEN:
        draw_xiao_small(24, 26)
        vtext("WIGLE.NET", 68, 24, 22, CYAN)
        vtext("SET API CREDENTIALS", 24, 86, 18, ORANGE)
        vtext("Run builder with credentials.json", 24, 120, 12, DIM)
        footer()
        return

    d = wigle_data or {}

    draw_xiao_small(24, 22)
    username = d.get("username") or "WIGLE.NET"
    vtext(fit(str(username), 150, 21), 64, 18, 21, CYAN)
    vright("WiGLE.NET", W - 15, 23, 11, GOLD)

    if d.get("join_date"):
        vtext("SINCE " + str(d.get("join_date")), 64, 49, 10, DIM)

    vtext("RANK", 15, 82, 11, DIM)
    rank_card(15, 97, 118, "GLOBAL", d.get("global_rank"), CYAN, True)
    rank_card(140, 103, W - 155, "MONTH", d.get("month_rank"), GOLD, False)

    gap = 6
    sw = (W - 30 - gap * 2) // 3
    sy = 158
    stat_card(15, sy, sw, "WI-FI", d.get("wifi"), PCB_GREEN_BRIGHT)
    stat_card(15 + sw + gap, sy, sw, "BLUETOOTH", d.get("bluetooth"), GOLD)
    stat_card(15 + (sw + gap) * 2, sy, sw, "CELL", d.get("cell"), CYAN)

    status_line(wigle_status)
    footer()


def refresh_wdgwars(now, continuing=False):
    global wdg_data, wdg_status, wdg_last_success, wdg_last_attempt, wdg_next_auto

    if not cfg.WDGWARS_ENABLED:
        return "SKIP"
    if not continuing:
        if not attempt_ready(now, wdg_last_attempt, cfg.WDGWARS_PAGE_ENTRY_COOLDOWN_MS):
            return "COOLDOWN"
        wdg_last_attempt = now
        wdg_next_auto = ticks_add(now, cfg.WDGWARS_REFRESH_MS)

    try:
        status, data = wdgwars.fetch(cfg.WDGWARS_API_KEY, wdg_data, NETWORK)
    except OSError:
        wdg_status = offline_status(wdg_data)
        return wdg_status
    if status == "OFFLINE" and wdg_data is not None:
        status = "CACHED"
    wdg_status = status
    if status == "LIVE" and data is not None:
        wdg_data = data
        wdg_last_success = now
    return status


def refresh_wigle(now, continuing=False):
    global wigle_data, wigle_status, wigle_last_success, wigle_last_attempt, wigle_next_auto

    if not cfg.WIGLE_ENABLED:
        return "SKIP"
    if not continuing:
        if not attempt_ready(now, wigle_last_attempt, cfg.WIGLE_PAGE_ENTRY_COOLDOWN_MS):
            return "COOLDOWN"
        wigle_last_attempt = now
        wigle_next_auto = ticks_add(now, cfg.WIGLE_REFRESH_MS)

    try:
        status, data = wigle.fetch(cfg.WIGLE_API_NAME, cfg.WIGLE_API_TOKEN, wigle_data, NETWORK)
    except OSError:
        wigle_status = offline_status(wigle_data)
        return wigle_status
    if status == "OFFLINE" and wigle_data is not None:
        status = "CACHED"
    wigle_status = status
    if status == "LIVE" and data is not None:
        wigle_data = data
        wigle_last_success = now
    return status


def queue_page_refresh(page_id):
    global wdg_refresh_pending, wigle_refresh_pending

    if page_id == "wdgwars":
        wdg_refresh_pending = "queued"
    elif page_id == "wigle":
        wigle_refresh_pending = "queued"


def refresh_page_entry(now, page_id):
    if page_id == "wdgwars":
        return refresh_wdgwars(now)
    elif page_id == "wigle":
        return refresh_wigle(now)
    return "SKIP"


def continue_pending_refreshes(now):
    global wdg_refresh_pending, wigle_refresh_pending

    if wdg_refresh_pending:
        status = refresh_wdgwars(now, continuing=(wdg_refresh_pending == "connecting"))
        if status != "CONNECTING":
            wdg_refresh_pending = None
        else:
            wdg_refresh_pending = "connecting"
    if wigle_refresh_pending:
        status = refresh_wigle(now, continuing=(wigle_refresh_pending == "connecting"))
        if status != "CONNECTING":
            wigle_refresh_pending = None
        else:
            wigle_refresh_pending = "connecting"


def refresh_background(now):
    global wdg_refresh_pending, wigle_refresh_pending

    if not wdg_refresh_pending and cfg.WDGWARS_ENABLED and ticks_elapsed(now, wdg_next_auto) >= 0:
        status = refresh_wdgwars(now)
        if status == "CONNECTING":
            wdg_refresh_pending = "connecting"
    if not wigle_refresh_pending and cfg.WIGLE_ENABLED and ticks_elapsed(now, wigle_next_auto) >= 0:
        status = refresh_wigle(now)
        if status == "CONNECTING":
            wigle_refresh_pending = "connecting"


def refresh_current(now, entered=False):
    current = PAGES[page_index]
    if entered:
        queue_page_refresh(current)
        return
    continue_pending_refreshes(now)
    refresh_background(now)


def draw():
    page_id = PAGES[page_index]
    if page_id == "main":
        draw_main()
    elif page_id == "wdgwars":
        draw_wdgwars()
    elif page_id == "wigle":
        draw_wigle()
    else:
        draw_link(page_id)


def update():
    global page_index, last_input, last_page_id

    now = badge.ticks
    old_page = PAGES[page_index]

    if ticks_elapsed(now, last_input) > cfg.INPUT_DELAY_MS:
        if badge.pressed(BUTTON_C):
            page_index = 0
            last_input = now
        elif badge.pressed(BUTTON_A):
            if page_index > 0:
                page_index -= 1
            last_input = now
        elif badge.pressed(BUTTON_B):
            if page_index < len(PAGES) - 1:
                page_index += 1
            last_input = now

    current = PAGES[page_index]
    entered = current != old_page or current != last_page_id
    last_page_id = current

    refresh_current(now, entered)
    draw()


def on_exit():
    pass


if BADGEWARE_READY:
    run(update)
